version: '3.8'
services:
  dev-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: nest-api
      MYSQL_USER: api 
      MYSQL_PASSWORD: 1234 
      MYSQL_ROOT_PASSWORD: 1234       
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - freecodecamp
networks:
  freecodecamp:
    
    